export const LEADS = [
  {
    id: "1",
    name: "Martin Torff",
    source: "Email Campaign",
    status: "New",
    lastContact: "Dec 14, 2024",
    checked: true,
  },
  {
    id: "2",
    name: "Cheyenne Lipshutz",
    source: "Email Campaign",
    status: "New",
    lastContact: "Dec 14, 2024",
    checked: false,
  },
  {
    id: "3",
    name: "Davis Baptista",
    source: "Social Media",
    status: "New",
    lastContact: "Dec 14, 2024",
    checked: false,
  },
  {
    id: "4",
    name: "Haylie Bator",
    source: "Email Campaign",
    status: "In Progress",
    lastContact: "Dec 14, 2024",
    checked: false,
  },
  {
    id: "5",
    name: "Maren Levin",
    source: "Social Media",
    status: "In Progress",
    lastContact: "Dec 14, 2024",
    checked: false,
  },
  {
    id: "6",
    name: "Phillip Dorwart",
    source: "Social Media",
    status: "Converted",
    lastContact: "Dec 14, 2024",
    checked: false,
  },
];
